tested CI

diff --git a/.github/workflows/tox.yml b/.github/workflows/tox.yml
--- a/.github/workflows/tox.yml
+++ b/.github/workflows/tox.yml
@@ -122,7 +122,7 @@ jobs:
         run: python3 -m pip freeze --all
 
       - name: Initialize tox envs ${{ matrix.passed_name }}
-        run: python3 -m tox --notest --skip-missing-interpreters false -vv -e py312
+        run: python3 -m tox --notest --skip-missing-interpreters false -vv
         timeout-minutes: 5 # average is under 1, but macos can be over 3
       - name: Restore pytest-ranking cache
         id: restore-pytest-ranking-cache
@@ -144,35 +144,35 @@ jobs:
           path: ${{ github.workspace }}/.tox/py312/.pytest_cache/v/pytest_ranking_data
           key: pytest-ranking-cache-${{ runner.os }}-${{ matrix.python }}-${{ github.run_id }}
 
-      - name: Combine coverage data
-        if: ${{ startsWith(matrix.passed_name, 'py') }}
-        # produce a single .coverage file at repo root
-        run: tox -e coverage
+      # - name: Combine coverage data
+      #   if: ${{ startsWith(matrix.passed_name, 'py') }}
+      #   # produce a single .coverage file at repo root
+      #   run: tox -e coverage
 
-      - name: Upload coverage data
-        if: ${{ startsWith(matrix.passed_name, 'py') }}
-        uses: codecov/codecov-action@v4
-        with:
-          name: ${{ matrix.passed_name }}
-          token: ${{ secrets.CODECOV_TOKEN }}
-          verbose: true # optional (default = false)
-          fail_ci_if_error: true
+      # - name: Upload coverage data
+      #   if: ${{ startsWith(matrix.passed_name, 'py') }}
+      #   uses: codecov/codecov-action@v4
+      #   with:
+      #     name: ${{ matrix.passed_name }}
+      #     token: ${{ secrets.CODECOV_TOKEN }}
+      #     verbose: true # optional (default = false)
+      #     fail_ci_if_error: true
 
-      - name: Archive logs
-        uses: actions/upload-artifact@v4
-        with:
-          name: logs-${{ matrix.name }}.zip
-          path: .tox/**/log/
+      # - name: Archive logs
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: logs-${{ matrix.name }}.zip
+      #     path: .tox/**/log/
 
-      - name: Report failure if git reports dirty status
-        run: |
-          git checkout HEAD -- src/ansiblelint/schemas/__store__.json
-          if [[ -n $(git status -s) ]]; then
-            # shellcheck disable=SC2016
-            echo -n '::error file=git-status::'
-            printf '### Failed as git reported modified and/or untracked files\n```\n%s\n```\n' "$(git status -s)" | tee -a "$GITHUB_STEP_SUMMARY"
-            exit 99
-          fi
+      # - name: Report failure if git reports dirty status
+      #   run: |
+      #     git checkout HEAD -- src/ansiblelint/schemas/__store__.json
+      #     if [[ -n $(git status -s) ]]; then
+      #       # shellcheck disable=SC2016
+      #       echo -n '::error file=git-status::'
+      #       printf '### Failed as git reported modified and/or untracked files\n```\n%s\n```\n' "$(git status -s)" | tee -a "$GITHUB_STEP_SUMMARY"
+      #       exit 99
+      #     fi
         # https://github.com/actions/toolkit/issues/193
   # codeql:
   #   name: codeql
